spring:

  data:
    mongodb:
      host: localhost

  application:
    name: stash

logging:
  level:
    root: INFO
    de.kodestruktor: DEBUG
    com:
      zaxxer: WARN
    org:
      apache: WARN
      hibernate: ERROR
      springframework: WARN
    springfox: WARN

auth:
  jwt:
    secret: aer8ohjoh2Eir2is4usheiSh
